/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as CertificatsRouteImport } from './routes/certificats'
import { Route as ComptabiliteRouteImport } from './routes/comptabilite'
import { Route as OrdonnancesRouteImport } from './routes/ordonnances'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as PatientsRouteImport } from './routes/patients'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatsRoute = CertificatsRouteImport.update({
  id: '/certificats',
  path: '/certificats',
  getParentRoute: () => rootRouteImport,
} as any)
const ComptabiliteRoute = ComptabiliteRouteImport.update({
  id: '/comptabilite',
  path: '/comptabilite',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdonnancesRoute = OrdonnancesRouteImport.update({
  id: '/ordonnances',
  path: '/ordonnances',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/certificats': typeof CertificatsRoute
  '/comptabilite': typeof ComptabiliteRoute
  '/ordonnances': typeof OrdonnancesRoute
  '/parametres': typeof ParametresRoute
  '/patients': typeof PatientsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/certificats': typeof CertificatsRoute
  '/comptabilite': typeof ComptabiliteRoute
  '/ordonnances': typeof OrdonnancesRoute
  '/parametres': typeof ParametresRoute
  '/patients': typeof PatientsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/certificats': typeof CertificatsRoute
  '/comptabilite': typeof ComptabiliteRoute
  '/ordonnances': typeof OrdonnancesRoute
  '/parametres': typeof ParametresRoute
  '/patients': typeof PatientsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/certificats'
    | '/comptabilite'
    | '/ordonnances'
    | '/parametres'
    | '/patients'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/certificats'
    | '/comptabilite'
    | '/ordonnances'
    | '/parametres'
    | '/patients'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/certificats'
    | '/comptabilite'
    | '/ordonnances'
    | '/parametres'
    | '/patients'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  CertificatsRoute: typeof CertificatsRoute
  ComptabiliteRoute: typeof ComptabiliteRoute
  OrdonnancesRoute: typeof OrdonnancesRoute
  ParametresRoute: typeof ParametresRoute
  PatientsRoute: typeof PatientsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificats': {
      id: '/certificats'
      path: '/certificats'
      fullPath: '/certificats'
      preLoaderRoute: typeof CertificatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comptabilite': {
      id: '/comptabilite'
      path: '/comptabilite'
      fullPath: '/comptabilite'
      preLoaderRoute: typeof ComptabiliteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ordonnances': {
      id: '/ordonnances'
      path: '/ordonnances'
      fullPath: '/ordonnances'
      preLoaderRoute: typeof OrdonnancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  CertificatsRoute: CertificatsRoute,
  ComptabiliteRoute: ComptabiliteRoute,
  OrdonnancesRoute: OrdonnancesRoute,
  ParametresRoute: ParametresRoute,
  PatientsRoute: PatientsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
