/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AnnuaireRouteImport } from './routes/annuaire'
import { Route as CertificatsRouteImport } from './routes/certificats'
import { Route as ComptabiliteRouteImport } from './routes/comptabilite'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as OrdonnancesRouteImport } from './routes/ordonnances'
import { Route as OrientationsRouteImport } from './routes/orientations'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as PersonnelRouteImport } from './routes/personnel'
import { Route as RappelsRouteImport } from './routes/rappels'
import { Route as TrackerRouteImport } from './routes/tracker'
import { Route as VaccinationsRouteImport } from './routes/vaccinations'
import { Route as HistoriqueIdRouteImport } from './routes/historique.$id'
import { Route as SuiviIndexRouteImport } from './routes/suivi.index'
import { Route as SuiviIdRouteImport } from './routes/suivi.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnuaireRoute = AnnuaireRouteImport.update({
  id: '/annuaire',
  path: '/annuaire',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatsRoute = CertificatsRouteImport.update({
  id: '/certificats',
  path: '/certificats',
  getParentRoute: () => rootRouteImport,
} as any)
const ComptabiliteRoute = ComptabiliteRouteImport.update({
  id: '/comptabilite',
  path: '/comptabilite',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdonnancesRoute = OrdonnancesRouteImport.update({
  id: '/ordonnances',
  path: '/ordonnances',
  getParentRoute: () => rootRouteImport,
} as any)
const OrientationsRoute = OrientationsRouteImport.update({
  id: '/orientations',
  path: '/orientations',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonnelRoute = PersonnelRouteImport.update({
  id: '/personnel',
  path: '/personnel',
  getParentRoute: () => rootRouteImport,
} as any)
const RappelsRoute = RappelsRouteImport.update({
  id: '/rappels',
  path: '/rappels',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackerRoute = TrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const VaccinationsRoute = VaccinationsRouteImport.update({
  id: '/vaccinations',
  path: '/vaccinations',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriqueIdRoute = HistoriqueIdRouteImport.update({
  id: '/historique/$id',
  path: '/historique/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SuiviIndexRoute = SuiviIndexRouteImport.update({
  id: '/suivi/',
  path: '/suivi/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuiviIdRoute = SuiviIdRouteImport.update({
  id: '/suivi/$id',
  path: '/suivi/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agenda': typeof AgendaRoute
  '/annuaire': typeof AnnuaireRoute
  '/certificats': typeof CertificatsRoute
  '/comptabilite': typeof ComptabiliteRoute
  '/documents': typeof DocumentsRoute
  '/journal': typeof JournalRoute
  '/messages': typeof MessagesRoute
  '/ordonnances': typeof OrdonnancesRoute
  '/orientations': typeof OrientationsRoute
  '/parametres': typeof ParametresRoute
  '/patients': typeof PatientsRoute
  '/personnel': typeof PersonnelRoute
  '/rappels': typeof RappelsRoute
  '/tracker': typeof TrackerRoute
  '/vaccinations': typeof VaccinationsRoute
  '/historique/$id': typeof HistoriqueIdRoute
  '/suivi/$id': typeof SuiviIdRoute
  '/suivi/': typeof SuiviIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agenda': typeof AgendaRoute
  '/annuaire': typeof AnnuaireRoute
  '/certificats': typeof CertificatsRoute
  '/comptabilite': typeof ComptabiliteRoute
  '/documents': typeof DocumentsRoute
  '/journal': typeof JournalRoute
  '/messages': typeof MessagesRoute
  '/ordonnances': typeof OrdonnancesRoute
  '/orientations': typeof OrientationsRoute
  '/parametres': typeof ParametresRoute
  '/patients': typeof PatientsRoute
  '/personnel': typeof PersonnelRoute
  '/rappels': typeof RappelsRoute
  '/tracker': typeof TrackerRoute
  '/vaccinations': typeof VaccinationsRoute
  '/historique/$id': typeof HistoriqueIdRoute
  '/suivi/$id': typeof SuiviIdRoute
  '/suivi': typeof SuiviIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agenda': typeof AgendaRoute
  '/annuaire': typeof AnnuaireRoute
  '/certificats': typeof CertificatsRoute
  '/comptabilite': typeof ComptabiliteRoute
  '/documents': typeof DocumentsRoute
  '/journal': typeof JournalRoute
  '/messages': typeof MessagesRoute
  '/ordonnances': typeof OrdonnancesRoute
  '/orientations': typeof OrientationsRoute
  '/parametres': typeof ParametresRoute
  '/patients': typeof PatientsRoute
  '/personnel': typeof PersonnelRoute
  '/rappels': typeof RappelsRoute
  '/tracker': typeof TrackerRoute
  '/vaccinations': typeof VaccinationsRoute
  '/historique/$id': typeof HistoriqueIdRoute
  '/suivi/$id': typeof SuiviIdRoute
  '/suivi/': typeof SuiviIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agenda'
    | '/annuaire'
    | '/certificats'
    | '/comptabilite'
    | '/documents'
    | '/journal'
    | '/messages'
    | '/ordonnances'
    | '/orientations'
    | '/parametres'
    | '/patients'
    | '/personnel'
    | '/rappels'
    | '/tracker'
    | '/vaccinations'
    | '/historique/$id'
    | '/suivi/$id'
    | '/suivi/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/agenda'
    | '/annuaire'
    | '/certificats'
    | '/comptabilite'
    | '/documents'
    | '/journal'
    | '/messages'
    | '/ordonnances'
    | '/orientations'
    | '/parametres'
    | '/patients'
    | '/personnel'
    | '/rappels'
    | '/tracker'
    | '/vaccinations'
    | '/historique/$id'
    | '/suivi/$id'
    | '/suivi'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agenda'
    | '/annuaire'
    | '/certificats'
    | '/comptabilite'
    | '/documents'
    | '/journal'
    | '/messages'
    | '/ordonnances'
    | '/orientations'
    | '/parametres'
    | '/patients'
    | '/personnel'
    | '/rappels'
    | '/tracker'
    | '/vaccinations'
    | '/historique/$id'
    | '/suivi/$id'
    | '/suivi/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AgendaRoute: typeof AgendaRoute
  AnnuaireRoute: typeof AnnuaireRoute
  CertificatsRoute: typeof CertificatsRoute
  ComptabiliteRoute: typeof ComptabiliteRoute
  DocumentsRoute: typeof DocumentsRoute
  JournalRoute: typeof JournalRoute
  MessagesRoute: typeof MessagesRoute
  OrdonnancesRoute: typeof OrdonnancesRoute
  OrientationsRoute: typeof OrientationsRoute
  ParametresRoute: typeof ParametresRoute
  PatientsRoute: typeof PatientsRoute
  PersonnelRoute: typeof PersonnelRoute
  RappelsRoute: typeof RappelsRoute
  TrackerRoute: typeof TrackerRoute
  VaccinationsRoute: typeof VaccinationsRoute
  HistoriqueIdRoute: typeof HistoriqueIdRoute
  SuiviIdRoute: typeof SuiviIdRoute
  SuiviIndexRoute: typeof SuiviIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annuaire': {
      id: '/annuaire'
      path: '/annuaire'
      fullPath: '/annuaire'
      preLoaderRoute: typeof AnnuaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificats': {
      id: '/certificats'
      path: '/certificats'
      fullPath: '/certificats'
      preLoaderRoute: typeof CertificatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comptabilite': {
      id: '/comptabilite'
      path: '/comptabilite'
      fullPath: '/comptabilite'
      preLoaderRoute: typeof ComptabiliteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ordonnances': {
      id: '/ordonnances'
      path: '/ordonnances'
      fullPath: '/ordonnances'
      preLoaderRoute: typeof OrdonnancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orientations': {
      id: '/orientations'
      path: '/orientations'
      fullPath: '/orientations'
      preLoaderRoute: typeof OrientationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personnel': {
      id: '/personnel'
      path: '/personnel'
      fullPath: '/personnel'
      preLoaderRoute: typeof PersonnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rappels': {
      id: '/rappels'
      path: '/rappels'
      fullPath: '/rappels'
      preLoaderRoute: typeof RappelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracker': {
      id: '/tracker'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof TrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vaccinations': {
      id: '/vaccinations'
      path: '/vaccinations'
      fullPath: '/vaccinations'
      preLoaderRoute: typeof VaccinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historique/$id': {
      id: '/historique/$id'
      path: '/historique/$id'
      fullPath: '/historique/$id'
      preLoaderRoute: typeof HistoriqueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suivi/': {
      id: '/suivi/'
      path: '/suivi'
      fullPath: '/suivi/'
      preLoaderRoute: typeof SuiviIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suivi/$id': {
      id: '/suivi/$id'
      path: '/suivi/$id'
      fullPath: '/suivi/$id'
      preLoaderRoute: typeof SuiviIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AgendaRoute: AgendaRoute,
  AnnuaireRoute: AnnuaireRoute,
  CertificatsRoute: CertificatsRoute,
  ComptabiliteRoute: ComptabiliteRoute,
  DocumentsRoute: DocumentsRoute,
  JournalRoute: JournalRoute,
  MessagesRoute: MessagesRoute,
  OrdonnancesRoute: OrdonnancesRoute,
  OrientationsRoute: OrientationsRoute,
  ParametresRoute: ParametresRoute,
  PatientsRoute: PatientsRoute,
  PersonnelRoute: PersonnelRoute,
  RappelsRoute: RappelsRoute,
  TrackerRoute: TrackerRoute,
  VaccinationsRoute: VaccinationsRoute,
  HistoriqueIdRoute: HistoriqueIdRoute,
  SuiviIdRoute: SuiviIdRoute,
  SuiviIndexRoute: SuiviIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
